name: Build and Deploy
on:
  push:
    branches:
      - development
      - main
  repository_dispatch:
    types: [webiny-publish]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .env
      run: |
        echo "NEXT_PUBLIC_WEBINY_API_URL=${{ secrets.NEXT_PUBLIC_WEBINY_API_URL }}" >> .env
        echo "NEXT_PUBLIC_GTM_KEY=${{ secrets.NEXT_PUBLIC_GTM_KEY }}" >> .env
        echo "WEBINY_API_SECRET=${{ secrets.WEBINY_API_SECRET }}" >> .env
        echo "NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL }}" >> .env
        echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
        echo "NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY }}" >> .env
        echo "NEXT_PUBLIC_GOOGLE_ANALYTICS_PROPERTY=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_PROPERTY }}" >> .env
        cat .env

    - name: Install and Build
      run: |
        yarn install
        yarn run build
        touch out/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.DEPLOYMENT_TOKEN }}
        branch: gh-pages
        folder: out
